// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_import from "./routes/api/import.ts";
import * as $api_reset from "./routes/api/reset.ts";
import * as $api_setCompleted from "./routes/api/setCompleted.ts";
import * as $index from "./routes/index.tsx";
import * as $Partners from "./islands/Partners.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/import.ts": $api_import,
    "./routes/api/reset.ts": $api_reset,
    "./routes/api/setCompleted.ts": $api_setCompleted,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Partners.tsx": $Partners,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
